// Profile 结构化生成（P1-17/18）：只写 projectRoot/generated/，绝不改 sourceRoot（模板 src）。
// 幂等：规范化 JSON（键排序）序列化 → 相同输入字节一致、digest 稳定；内容不变不重写。
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";

function stableStringify(value) {
  if (value === null || typeof value !== "object") return JSON.stringify(value);
  if (Array.isArray(value)) return "[" + value.map(stableStringify).join(",") + "]";
  const keys = Object.keys(value).sort();
  return "{" + keys.map((k) => JSON.stringify(k) + ":" + stableStringify(value[k])).join(",") + "}";
}

export function generateProfile({ profile, sourceRoot, projectRoot }) {
  if (profile == null || typeof profile !== "object") throw new Error("normalized profile required");
  const root = resolve(projectRoot);
  const canonical = stableStringify(profile);
  const digest = createHash("sha256").update(canonical).digest("hex");
  const json = JSON.stringify(profile, null, 2) + "\n";
  const ts = "// AUTO-GENERATED by generate-profile.mjs — DO NOT EDIT\n" +
    "// digest: " + digest + "\n" +
    "export const PROFILE = " + json + " as const;\n";

  const files = [
    { rel: "generated/profile.json", content: json },
    { rel: "generated/profile.config.ts", content: ts },
  ];
  mkdirSync(join(root, "generated"), { recursive: true });
  const generatedFiles = [];
  for (const f of files) {
    const abs = join(root, f.rel);
    if (!(existsSync(abs) && readFileSync(abs, "utf-8") === f.content)) {
      writeFileSync(abs, f.content);
    }
    generatedFiles.push(f.rel);
  }
  return { digest, generatedFiles };
}
