// Token 单源生成器（P1-21）：tokens/source.json（唯一手改）→ tokens.ts / theme.css / theme.scss（生成输出）
// 失败即抛：三层缺失、循环引用、未知引用、错误单位（uni 端只认 #hex / rpx / ms / s / % / 纯数）。
import { createHash } from "node:crypto";
import { mkdirSync, readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, resolve } from "node:path";

const COLOR_RE = /^#[0-9A-Fa-f]{3,8}$/;
// 2026-09-19：深色主题还原引入 rgba() 字面值（旧端 gold-70/50/30 实测）；rgb/rgba 为标准 CSS 颜色函数，wxss/ttss 均支持
const RGBA_RE = /^rgba?\(\s*\d+\s*,\s*\d+\s*,\s*\d+\s*(,\s*(0|1|0?\.\d+)\s*)?\)$/;
const DIM_RE = /^-?\d+(\.\d+)?(rpx|ms|s|%)$/;
const NUM_RE = /^-?\d+(\.\d+)?$/;
const REF_RE = /^\{(primitive|semantic)\.([A-Za-z0-9_]+)\}$/;
// 2026-09-22 主人「风格和主题请绑定 token」：字体族（如 HarmonyOS-Sans-SC / NotoSerifSC-Bold）本质是**平台字体资源名**，
// 也应有单一事实源 ⇒ 仅放行 `fontFamily*` 键（CSS 标识符或逗号分隔族名），其它键仍只认 #hex/rpx/ms/s/%/纯数。
const FONT_FAMILY_RE = /^[A-Za-z][\w-]*(?:\s+[A-Za-z][\w-]*)*(?:\s*,\s*[A-Za-z][\w-]*(?:\s+[A-Za-z][\w-]*)*)*$/;

function kebab(name) {
  return name.replace(/([a-z0-9])([A-Z])/g, "$1-$2").toLowerCase();
}

function checkLiteral(layer, key, value) {
  if (typeof value === "number") return; // component 纯数（档位计数）
  if (typeof value !== "string") throw new Error("invalid value type in " + layer + "." + key);
  if (COLOR_RE.test(value) || RGBA_RE.test(value) || DIM_RE.test(value) || NUM_RE.test(value)) return;
  if (key.startsWith("fontFamily") && FONT_FAMILY_RE.test(value)) return;
  throw new Error("bad unit in " + layer + "." + key + ": " + value + " (uni 只认 #hex/rpx/ms/s/%/纯数)");
}

function sortedObj(o) {
  const out = {};
  for (const k of Object.keys(o).sort()) out[k] = o[k];
  return out;
}

export function generateTokens({ sourceFile, outputDir }) {
  const src = JSON.parse(readFileSync(resolve(sourceFile), "utf-8"));
  for (const layer of ["primitive", "semantic", "component"]) {
    if (src[layer] == null || typeof src[layer] !== "object" || Array.isArray(src[layer])) {
      throw new Error("source missing layer: " + layer);
    }
  }

  for (const [k, v] of Object.entries(src.primitive)) {
    if (typeof v === "string" && v.startsWith("{")) throw new Error("primitive." + k + " must be literal");
    checkLiteral("primitive", k, v);
  }

  const memo = new Map();
  const visiting = new Set();
  // 注意：命名 resolveRef，避免遮蔽 node:path 的 resolve（首版即因遮蔽触发 TDZ）
  function resolveRef(layer, key) {
    const cacheKey = layer + "." + key;
    if (memo.has(cacheKey)) return memo.get(cacheKey);
    if (visiting.has(cacheKey)) throw new Error("circular reference at " + cacheKey);
    const raw = src[layer] ? src[layer][key] : undefined;
    if (raw === undefined) throw new Error("unknown reference: " + cacheKey);
    if (typeof raw === "number") { memo.set(cacheKey, raw); return raw; }
    const m = REF_RE.exec(raw);
    let out;
    if (m) {
      visiting.add(cacheKey);
      out = resolveRef(m[1], m[2]);
      visiting.delete(cacheKey);
    } else {
      checkLiteral(layer, key, raw);
      out = raw;
    }
    memo.set(cacheKey, out);
    return out;
  }

  const resolved = { primitive: {}, semantic: {}, component: {} };
  for (const k of Object.keys(src.primitive)) resolved.primitive[k] = resolveRef("primitive", k);
  for (const k of Object.keys(src.semantic)) resolved.semantic[k] = resolveRef("semantic", k);
  for (const k of Object.keys(src.component)) resolved.component[k] = resolveRef("component", k);

  const ordered = { primitive: sortedObj(resolved.primitive), semantic: sortedObj(resolved.semantic), component: sortedObj(resolved.component) };
  const digest = createHash("sha256").update(JSON.stringify(ordered)).digest("hex");

  const cssLines = ["/* AUTO-GENERATED by generate-tokens.mjs — DO NOT EDIT */", "/* digest: " + digest + " */", ":root {" ];
  const scssLines = ["// AUTO-GENERATED by generate-tokens.mjs — DO NOT EDIT", "// digest: " + digest];
  // 2026-09-19：theme.scss/theme.css 增发 primitive 层——抖音 TTSS 不支持 CSS 变量，样式全面改走
  // scss 编译期常量（v-bind→$var），primitive 间距等也需 $ 变量形态；三产物仍同源同 digest
  for (const layer of ["primitive", "semantic", "component"]) {
    for (const k of Object.keys(ordered[layer])) {
      const v = ordered[layer][k];
      cssLines.push("  --" + kebab(k) + ": " + v + ";");
      scssLines.push("$" + kebab(k) + ": " + v + ";");
    }
  }
  cssLines.push("}");

  const ts = [
    "// AUTO-GENERATED by generate-tokens.mjs — DO NOT EDIT",
    "// digest: " + digest,
    "export const tokens = " + JSON.stringify(ordered, null, 2) + " as const;",
    "export type TokenDigest = \"" + digest + "\";",
    "",
  ].join("\n");

  const out = resolve(outputDir);
  mkdirSync(out, { recursive: true });
  const files = [
    { name: "tokens.ts", content: ts },
    { name: "theme.css", content: cssLines.join("\n") + "\n" },
    { name: "theme.scss", content: scssLines.join("\n") + "\n" },
  ];
  const written = [];
  for (const f of files) {
    const abs = join(out, f.name);
    if (!(existsSync(abs) && readFileSync(abs, "utf-8") === f.content)) writeFileSync(abs, f.content);
    written.push(f.name);
  }
  return { digest, files: written };
}
