import { request } from './http.uts'

// 导航栏接口
export const getImage = async (method: string, params?: any) => {
	const res = await request({
		url: '/wechat/carousels',
		method: (method || 'GET').toUpperCase() as any,
		data: params,
		showLoading: false,
	})
	return res
}

// 客片一级接口
export const getalbum = async (method: string, params?: any) => {
	const res = await request({
		url: '/wechat/album',
		method: (method || 'GET').toUpperCase() as any,
		data: params,
		showLoading: false,
	})
	return res
}

// 客片详情页接口
export const getalbumDetail = async (method: string, params?: any) => {
	const res = await request({
		url: '/wechat/album/detail',
		method: (method || 'GET').toUpperCase() as any,
		data: params,
		showLoading: false,
	})
	return res
}